### PR TITLE
Added Artifacts, Rituasl & Tomes

### PR DESCRIPTION
**Pull request by Vogliadicone**
I added all the Open Mythos Artifacts, Rituals & Tomes and added the new Rituals to the Entities gear.

I hope, I did everything right. But better check before (it's just my 2nd PR so it's possible, that I did something wrong).

I didn't update the links to the Rituals in the Entities text description. I also didn't add any fandy new icons for the artifacts. This is something for another update.

Speaking about possible updates: What do you think about exchanging the images & tokens one day with AI art? Since I can't draw, that would be an option to have nice (open source) images & tokens for all creatures & icons.

### CODE REVIEW

**Comment by stories-with-dice** [comment]
Thanks a lot for this! I will have time to check tomorrow or Friday.

**Comment by stories-with-dice** [comment]
Actually, I already see an issue. There are no changed files in this PR. I'm not sure what happened here.


image

**Comment by Vogliadicone** [comment]
Strange, don't know how that happened. I'm away from my main computer for the next three weeks, so I can't check it right now.

I could share with you all the files via Google Drive tomorrow and you push a release. Or I could try to set up Visual Studio on my Notebook at the weekend and see if I can make a PR.

**Comment by stories-with-dice** [comment]
You can upload to drive and I can look into it.

**Comment by Vogliadicone** [comment]
Here you have the updated pack folder, changelog and module.json. The rest stays the same.
https://drive.google.com/file/d/1Rra5N1ZEc64wLcQIx0vWYPtv81yxGIz7/view?usp=sharing

**Comment by stories-with-dice** [comment]
I tried again, with the new files. But I don't see anything new. This is what I see in my Foundry:

image

**Comment by Vogliadicone** [comment]
Please try again with this files. I copied them from my local module into your module and they contained the new items (but I had to disable and reactivate the module):
https://drive.google.com/file/d/1Ru8SjgXhEWt6NTU1nlPQoJ8Z5tExL5Q3/view?usp=sharing

**Comment by stories-with-dice** [comment]
I don't have access to that link.

**Comment by Vogliadicone** [comment]
Sorry, my fault. Now it should work:
https://drive.google.com/file/d/1Ru8SjgXhEWt6NTU1nlPQoJ8Z5tExL5Q3/view?usp=sharing

**Comment by stories-with-dice** [comment]
This works! Can you add these files to your PR?

**Comment by Vogliadicone** [comment]
I can, but not before the beginning of October when I'm back at my main computer with Visual Studio. If you wanna push an update before, you would have to exchange the files yourself.

**Comment by stories-with-dice** [comment]
I can't upload to this PR, as it's based on your repo.

**Comment by Vogliadicone** [comment]
But you could close this PR and create a new one with these files.

**Comment by stories-with-dice** [comment]
Just did. Thanks again for your contributions! I added you to the contributors, both in the README and the `module.json`.

Closed by #4

**Comment by Vogliadicone** [comment]
Thanks! I updated the module and everything worked as expected.

**Pull request closed without merging**
